### ISSUE TITLE
Pr.2: sucesores tiene parentesis de mas

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#10]
https://github.com/IanGhioni/EstrD2023s1/blob/0cc59fc0fbabca8dc6b9f07f63a28b0275b85ea0/tp-2/tp-2.hs#L12-L14

El parentesis que encapsula el retorno de la funcion no cumple ningun proposito

**Comment by IanGhioni** [comment]
Corregido
