### ISSUE TITLE
Pr.2: En cuantosDeTipo_De_LeGananATodosLosDe_ estás dependiendo de la forma en que un Pokémon le gana a otro

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#14]
https://github.com/IanGhioni/EstrD2023s1/blob/0cc59fc0fbabca8dc6b9f07f63a28b0275b85ea0/tp-2/tp-2.hs#L229-L240

¿Qué sucede si la forma en que un Pokémon le gana a otro cambiase? Tu función debería cambiar, pero no es adecuado que sea así…

**Comment by IanGhioni** [comment]
Hola Lorenzo, no entiendo bien esta correcion. Si la forma en que un Pokémon le gana a otro cambiase, no se veria afectada unicamente la funcion puedeDerrotarAlPokemon  y la funcion puedeDerrotarATodosLosPokemon seguiria funcionando??

**Comment by LorenzoFerraces** [comment]
Tenes toda la razon, me fallo la vista completamente viendo que estaba esa funcion en el medio que hace exactamente lo que hay que hacer en este caso, mil disculpas

**Comment by IanGhioni** [comment]
Entonces esta bien? O el issue sigue abierto por algun otro motivo?
