### ISSUE TITLE
Pr.1: primerYUltimoDia es incorrecta

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#2]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L76-L77

No entiendo muy bien el por que le agregaste a la definicion que esta funcion recibe dos dias por parametro, ni cual es la funcion de esos parametros en tu funcion, pero se supone que el tipado de esta funcion seria algo asi:

primerYUltimoDia :: (DiaDeLaSemana, DiaDeLaSemana)

el resto de la funcion te lo dejo a vos ;)

**Comment by IanGhioni** [comment]
Corregido
