### ISSUE TITLE
Pr.3: en cantTesoroEntre estas haciendo dos recursiones

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#24]
https://github.com/IanGhioni/EstrD2023s1/blob/78115d0b32a5f436b6d6250509ed1e909015a27f/tp-3/tp-3.hs#L109-L130

En tu funcion haces recursion sobre el Camino y adentro estas metiendo recursion sobre los numeros, para despues pasar la recursion a una subtarea.
Lo mas feliz seria hacer una unica recursion sobre el Camino y tener los numeros como caso base de tu recursion

**Comment by IanGhioni** [comment]
Arreglado creo @LorenzoFerraces este y los demas issues

**Comment by LorenzoFerraces** [comment]
Fijate el detallito que deje en simplificar, pero el resto esta todo muy bien
