### ISSUE TITLE
Pr.1: la funcion vieneDespues es incorrecta

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#3]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L89-L91

es mas un malentendido de el enunciado, la idea es que aplique a todos los dias despues de uno y no solo al que esta inmediatamente despues. Esto se simplifica mucho con el uso de una subtarea que definiste vos mismo antes

**Comment by IanGhioni** [comment]
Corregido
