### ISSUE TITLE
Pr.1: La función yTambien hace doble PM

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#4]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L113-L115

Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by IanGhioni** [comment]
Corregido
