### ISSUE TITLE
Pr.1: Hay "miedo al booleano" en la función oBien

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#5]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L117-L121

Básicamente, preguntás si algo es True para devolver True y cuando no es True devolvés False.
Por ejemplo, escribir if cond then True else False en lugar de cond, que es equivalente. 
O en forma de PM:
	f True = True
	f _    = False

**Comment by IanGhioni** [comment]
Resuelto

**Comment by LorenzoFerraces** [comment]
Un interesante uso de las leyes logicas para convertir la disyuncion en conjuncion pero no es lo que buscamos, ibas bien haciendolo con PM pero la idea es que puedas resolverlo haciendo PM sobre uno solo de los parametros

**Comment by IanGhioni** [comment]
Corregido
