### ISSUE TITLE
Pr.1: tu funciones son muy poco resiliente a cambios

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#6]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L176-L194

En estas funciones usas dos observadoras que definiste para acceder a los pokemon del entrenador en vez de hacerlo por PM, esto no es inherentemente malo pero la forma en la que lo haces hace que si cambiamos la estructura de entrenador a que tenga una tupla o una lista de pokemon, tengas que cambiar todo el codigo de estas funciones

**Comment by IanGhioni** [comment]
Corregido
