### ISSUE TITLE
Pr.1: La función unoSiElTipoCoincide tiene demasiadas responsabilidades y su nombre no es feliz

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#7]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L186-L190

Es uno o cero ¿en qué casos? Por otra parte, podés separarla en dos funciones, cada una de las cuales haga la parte que le toca

**Comment by IanGhioni** [comment]
Corregido

**Comment by LorenzoFerraces** [comment]
Sigue siendo poco feliz como tu funcion hace la comparacion y evalua que numero devolver, la idea es que esa funcion se encargue unicamente de devolver uno o cero segun el valor de verdad de la expresion que le pases

**Comment by IanGhioni** [comment]
Corregido
