### ISSUE TITLE
Pr.1: La función juntarPokemon no es eficaz, porque tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by LorenzoFerraces** [IanGhioni/EstrD2023s1#8]
https://github.com/IanGhioni/EstrD2023s1/blob/558fd761fa679e27d7a9a706e2432d13fdd42453/tp-1/tp-1.hs#L192-L194

Sería bueno tener una subtarea que dado un único entrenador diera la lista de sus Pokemon, y usarla 2 veces

**Comment by IanGhioni** [comment]
Corregido
